### ISSUE TITLE
`wrap` has to be stateless?

### ISSUE THREAD

**Issue by willtebbutt** [tpgillam/TimeDag.jl#25]
[In the docs for `wrap`](https://invenia.github.io/TimeDag.jl/dev/reference/creating_ops/) it is stated that "It is assumed that f is stateless (this will therefore not work with closures).". Is this strictly true? Could you explain why this is necessary? Is it related to purity?

**Comment by tpgillam** [comment]
TimeDag needs to be able to manage state internally — among other things, making the same call to `evaluate` twice (with the same node(s) and time range) should always give the same answer.

If you `wrap` some function that depends on (or, especially, mutates) some _external_ state, then this property can be violated — since effectively you now have an object which could give different answers when called for a second time with the same arguments.

It gets worse if you were to wrap multiple things depending on the same global state, and if you were to depend on the order of evaluation, since `TimeDag` reserves the right to evaluate things in whatever order it likes :)

**Comment by tpgillam** [comment]
Currently any state is represented as an instance of a struct which inherits from `NodeEvaluationState`. It **is** possible to make `wrap` handle statefulness, but then it starts to look quite similar to just creating the node "by hand". See e.g. `history`: https://github.com/invenia/TimeDag.jl/blob/main/src/ops/history.jl#L1-L39

It might be possible to remove a *small* amount of boilerplate by expanding `wrap`, although I'm in two minds about whether it'd be a good thing.

**Comment by willtebbutt** [comment]
I see. I guess I'm imagining a use-case in which there's no risk of the "state" associated with your closure changing over time (so the closure is best thought of as a member of a parametric family of (pure) functions).

Something like:
```julia
function make_closure(a)
    my_closure(x) = a + x
    return my_closure
end
wrap(make_closure(5.0))
```
My reasoning being that there's no risk of accidentally mutating the `a` field of any given instance of `my_closure`.

Or could this still potentially cause problems?

**Comment by tpgillam** [comment]
```
julia> TimeDag.wrap(make_closure(5.0))
(::TimeDag.Wrapped{var"#my_closure#9"{Float64}(5.0)}) (generic function with 1 method)
```
So this is actually fine, because `5.0` is immutable. And it works! But
```
julia> TimeDag.wrap(make_closure([5.0]))
ERROR: TypeError: in Type, in parameter, expected Type, got a value of type var"#my_closure#9"{Vector{Float64}}
```
blow up in some cryptic way (I don't know why so cryptic), basically because it's had to actually create some kind of closure object.

**Comment by tpgillam** [comment]
I guess in this *particular* case we, the user, know it's fine because `[5.0]` is an rvalue (to use C++ lingo) — i.e. the local frame doesn't have a reference to it, so can't mutate it. I have no idea if Julia can detect the difference between
```
f([5.0])
```
and
```
x = [5.0]
f(x)
```

**Comment by willtebbutt** [comment]
I don't think that Julia can tell the difference unfortunately.

> blow up in some cryptic way (I don't know why so cryptic), basically because it's had to actually create some kind of closure object.

Ah interesting -- I see why this is the case. You've got an interesting implementation for `Wrapped`! To be honest, I'm not totally sure why your implementation works for the closure at all. I guess Julia is smart enough to know it's a singleton or something....

Anyway, if you implemented `Wrapped` as
```julia
struct Wrapped{Tf} <: Function
    f::Tf
    time_agnostic::Bool
end
@inline function (wrapped::Wrapped)(x, rest...; kwargs...)
    return apply(wrapped.f, x, rest...; time_agnostic=wrapped.time_agnostic, kwargs...)
end
```
I imagine the more complicated closure with an array in could be made to work.

**Comment by tpgillam** [comment]
So the reason that `Wrapped` is implemented the way it is is to ensure that the compiler knows the function & value of `time_agnostic` at compile time — basically this permits some rather crucial inlining, since they are depended upon in the inner loop in the alignment code. Without this, you end up with moderate overhead from runtime switching&dispatch... (I vaguely remember noting something about this on the docstring to `time_agnostic` and related functions).

Possibly we could have something more permissive for non-function types (i.e. closures / callable objects), although I still worry about mutability guarantees. I consider it a feature that it doesn't allow things like `x=[5.0]; wrap(make_closure(x)); x[1] = 6.0` :)

Down the line it might also end up being handy when thinking about parallelising schedulers too — I imagine life gets a lot more fiddly if we want to permit arbitrary closures, perhaps?

I am aware that (generally) I err on the side of strictness where possible, just to remove cases I need to think about.

**Comment by tpgillam** [comment]
But I'd also say that I definitely think we could make writing stateful node ops a little less boiler-plate-y, if/when that ends up being annoying.
